### ISSUE TITLE
not installing csv_import _issues plugin

### ISSUE THREAD

**Issue by johnp2686** [stpl/csv_import_issues#1]
Hello,

 I am using redmine 2.2.4 and i will try to installed csv_import _issue plugin i cannot installing ,anyone help regarding this issue

**Comment by stpl** [comment]
Hi John, Could you let us know what exact issue are you facing.

**Comment by johnp2686** [comment]
I get plugin ur github account when I do rake the paperclip gem not install properly getting error (var/lib/paperclip/Lib/)

**Comment by johnp2686** [comment]
I cannot able to installed paperclip it is hitting error
