### ISSUE TITLE
users rights / groups

### ISSUE THREAD

**Issue by cobalt74** [stpl/csv_import_issues#12]
if the user is in a group that does not have rights to import and is also manager (with the rights of imports) then import issues shortcuts not displayed.

**Comment by stpl** [comment]
@cobalt74 , I think you are facing below case :

A user has roles :
- Manager, has right to Import, for ProjectA .
- Developer, has right to Import, for ProjectB. This role is assigned via a Group.

This user will Import issues for ProjectA but will not be able to Import in ProjectB.

It is redmine functionality not an issue, The roles are assigned to a user via a project.

Please let me know if I'm not clear.

**Comment by cobalt74** [comment]
thank you ... but

1 user "manager" and belonging to the group of developers on the project A can't import issues
1 user "manager" on Project A can import issues

**Comment by stpl** [comment]
@cobalt74 Thanks for reporting issue. I have fixed this. Please try with latest code and reopen if you face any issue.
