### ISSUE TITLE
if the csv file has chinese word,plugin import failed

### ISSUE THREAD

**Issue by samrain** [stpl/csv_import_issues#13]
ActionView::Template::Error (incompatible character encodings: UTF-8 and ASCII-8BIT):
    26:         <% @csv_rows[0].each_with_index do |value, index| %>
    27:           <tr class="<%= cycle('odd', 'even') %> issue child parent">
    28:                     <td> <%= value %> </td>
    29:                     <td> <%= @csv_rows[1][index] %> </td>
    30:                     <% @options = params[:options][index] if params[:import] %>
    31:                     <td>
    32:                       <%= select_tag :options, options_for_select(@query, :selected => @options), {:name => "options[]", :prompt => "No Match (Skip)"} 
  activesupport (3.2.19) lib/active_support/core_ext/string/output_safety.rb:135:in `concat'
  activesupport (3.2.19) lib/active_support/core_ext/string/output_safety.rb:135:in`concat'
  actionpack (3.2.19) lib/action_view/buffers.rb:11:in `<<'

**Comment by samrain** [comment]
I find the bug in the finalize.html.erb.
pls see my pull request

**Comment by stpl** [comment]
Hi @samrain 
Thanks for the pull request, we have merged it.
