### ISSUE TITLE
Empty redmine fields list

### ISSUE THREAD

**Issue by szaffarano** [stpl/csv_import_issues#4]
When I try to import a simple csv file (only one row with simple data), the preview page renders an empty list in the "redmine fields" column (only "No Match (Skip)" option).

Seems that

``` ruby
Query.new(:column_names => Setting.issue_list_default_columns).available_columns
```

(in csv_imports_controller.rb file, line 124) returns always an empty list.

I'm working with:
- Ubuntu 12.04 precise
- Ruby 2.1.1p76
- Redmine 2.5.1
- Rails 3.2.17

**Comment by tomolimo** [comment]
Hello,
I've got the same problem than you but with a different environment:
- Windows 7 64bits
- Ruby 1.9.3p484
- Rails 3.2.17
- Redmine 2.5.1

I happen to track down this trouble to the same point!

Did you find a solution for this trouble?
Thank you,
Tomolimo

**Comment by j-freuden** [comment]
Same problem with following environment:
- Ubuntu 14.04
- Ruby 2.0.0p481
- Rails 3.2.18
- Redmine 2.5.1

**Comment by szaffarano** [comment]
Meanwhile we are using [issuefy plugin](http://github.com/tchx84/issuefy)

**Comment by stpl** [comment]
Hi can you give it a try now. Have fixed it. 0.0.2 tag or checkout master. Thanks

**Comment by stpl** [comment]
I am closing it for now. Please re-open if you still have issues with this.

**Comment by szaffarano** [comment]
Thank you!
Version 0.0.2 fixed my issue :)
