### ISSUE TITLE
Installed but can't find how to use it

### ISSUE THREAD

**Issue by maxtango** [stpl/csv_import_issues#5]
Hello,

Redmine version: 2.5.1.stable.13171
Ruby version: 2.0.0-p481 (2014-05-08) [x86_64-linux]
Rails version: 3.2.18

I have installed the plugin succusfully, but can't see how to enabme the plugin on projects.
I have enbled it for the role, but deosn't change anything.

Thanks in advance,

Maxtango

**Comment by stpl** [comment]
Can you send the screenshot of plugins installed on your Redmine instance and role screenshot where you have selected the permissions. 
Then please send me screenshot of the project setting that could indicate you have added user with right role. 
Once you enable it on the role, user logged in if has access to the project in the given role will see an option to import issues on "issues" page - "Import from csv". 
It should then take you to the page where you can select CSV.

**Comment by maxtango** [comment]
It just resolved. I created a new project from scratch, and the "Import from CSV" link appeared.
Thank you for your job. This issue is closed for me.
